-- ============================================================
--  知渊 · Supabase 建表脚本（云同步 / 数据持久化）
-- ------------------------------------------------------------
--  使用方法：
--    1. 打开 Supabase 控制台 → 左侧 SQL Editor → New query
--    2. 整段复制粘贴本文件内容，点击 Run
--    3. 回到知渊，登录云端账号，即可自动同步
--
--  本脚本是幂等的：可以重复执行，不会破坏已有数据。
-- ============================================================


-- ------------------------------------------------------------
-- 表 1：user_state —— 通用用户状态表
-- ------------------------------------------------------------
-- 用于同步以下 4 类数据（按 key 区分，data 存 JSON 快照）：
--   key = 'kc'     知识中心（原始资料层 / 知识单元层 / 成果层）
--   key = 'inbox'  待整理箱（待确认 / 已沉淀 / 知识缺口 / 知识冲突）
--   key = 'proj'   项目列表（含复盘内容）
--   key = 'recall' 每日知识回溯日志
--
-- 采用 JSON 快照而非细粒度分表的原因：
--   个人知识库数据量小（通常数百条），前端本就全量加载；
--   快照同步实现简单、无迁移成本，且天然支持结构演进。
-- ------------------------------------------------------------
create table if not exists public.user_state (
  user_id    uuid        not null references auth.users(id) on delete cascade,
  key        text        not null,
  data       jsonb       not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

create index if not exists user_state_user_idx on public.user_state (user_id);

alter table public.user_state enable row level security;

-- 行级安全：每个用户只能读写自己的数据
drop policy if exists "user_state_select_own" on public.user_state;
create policy "user_state_select_own" on public.user_state
  for select using (auth.uid() = user_id);

drop policy if exists "user_state_insert_own" on public.user_state;
create policy "user_state_insert_own" on public.user_state
  for insert with check (auth.uid() = user_id);

drop policy if exists "user_state_update_own" on public.user_state;
create policy "user_state_update_own" on public.user_state
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "user_state_delete_own" on public.user_state;
create policy "user_state_delete_own" on public.user_state
  for delete using (auth.uid() = user_id);


-- ------------------------------------------------------------
-- 表 2：records —— 快速速记记录
-- ------------------------------------------------------------
-- 首页「快速收集」写入的原始速记。若你的项目里已存在该表，
-- 下面的 create table if not exists 会自动跳过，不影响已有数据。
-- ------------------------------------------------------------
create table if not exists public.records (
  id      bigint generated by default as identity primary key,
  user_id uuid        not null references auth.users(id) on delete cascade,
  type    text        not null default '灵感',
  content text        not null,
  ts      timestamptz not null default now()
);

create index if not exists records_user_ts_idx on public.records (user_id, ts desc);

alter table public.records enable row level security;

drop policy if exists "records_select_own" on public.records;
create policy "records_select_own" on public.records
  for select using (auth.uid() = user_id);

drop policy if exists "records_insert_own" on public.records;
create policy "records_insert_own" on public.records
  for insert with check (auth.uid() = user_id);

drop policy if exists "records_update_own" on public.records;
create policy "records_update_own" on public.records
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "records_delete_own" on public.records;
create policy "records_delete_own" on public.records
  for delete using (auth.uid() = user_id);


-- ------------------------------------------------------------
-- 自动维护 updated_at
-- ------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_state_touch on public.user_state;
create trigger user_state_touch
  before update on public.user_state
  for each row execute function public.touch_updated_at();


-- ------------------------------------------------------------
-- 校验：执行完成后运行下面这句，应能看到两张表
-- ------------------------------------------------------------
-- select table_name from information_schema.tables
--   where table_schema = 'public' and table_name in ('user_state','records');
